services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
  redis:
    image: "redis:7.2-alpine"
  prometheus:
    image: "prom/prometheus:v2.47.2"
    volumes:
      - "./prometheus:/etc/prometheus"
    ports:
      - "9090:9090"

