services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
  redis:
    image: "redis:7.2-alpine"

